### ISSUE TITLE
Possible bugs in your mod that are interfering with others

### ISSUE THREAD

**Issue by Sunconure11** [Liahim85/SaltyMod_1.10.2#6]
https://paste.dimdev.org/oyudotihug.mccrash

https://paste.dimdev.org/utepomecaf.mccrash

https://paste.dimdev.org/qoqojonixi.mccrash

https://paste.dimdev.org/fadujureku.mccrash

https://paste.dimdev.org/ayulocatal.mccrash

https://paste.dimdev.org/patokayise.mccrash

Salty mod is implicated in a few of them

**Comment by Liahim85** [comment]
I do not see any mention of salt in the crash log.
The problem disappears if you remove the mod?

**Comment by Sunconure11** [comment]
https://paste.dimdev.org/ayulocatal.mccrash

This particular log mentions salt. I have not tested that yet, as it appears to be several mods conflicting, and I'm trying to figure out what is going on.

>     at ru.liahim.saltmod.world.SaltOreGenerator.generateOverworld(SaltOreGenerator.java:31)
>     at ru.liahim.saltmod.world.SaltOreGenerator.generate(SaltOreGenerator.java:22)

**Comment by Liahim85** [comment]
It's just the ore generation, as well as in other specified modes. It seems to me that some mod crashes just during this generation.

**Comment by Robijnvogel** [comment]
@Liahim85 Your salt generator causes a new chunk to be generated, probably because it is trying to generate an ore-vein across a chunk border or your ore generator updates adjacent blocks. It seems to be the latter:
```log
at net.minecraft.world.World.markAndNotifyBlock(World.java:390)
```
Either way, it shouldn't. It is one of those things that Forge warns users for in their log. It can cause log spam and "cascading chunk lag."

To fix this, you should probably call `net.minecraft.world.World.setBlockState` with a different value for the  `flag` parameter that doesn't cause neighbouring blocks to receive an update.

About the crash itself: I still believe that a lot of Sunconure's crashes are caused by the generation of a new chunk whenever this generation is not a result of player-entity chunk loading. I doubt that you're directly responsible for any of them.

**Comment by Liahim85** [comment]
Try it!
https://cloud.mail.ru/public/5uYn/hPzawwvH4
If everything works, I will update the file on the site.

**Comment by Sunconure11** [comment]
I am no longer seeing any crashes that might be connected to your mod.
